/* ============================================================
 * 《汉使》Han Envoy — Phase 2.5 Act 0 示例数据
 *
 * 本文件仅提供 Act 0 阶段的设计预览和数据结构示例。
 * 尚未接入当前游戏主流程，不影响 Phase 2 已有功能。
 * ============================================================ */

import type { PreparationAction, IntelItem, EvidenceItem, InvestigationOutcome } from "./preCourtTypes";

/* ================================================================
 * 示例准备行动
 * ================================================================ */

export const PRE_COURT_ACTIONS: PreparationAction[] = [
  {
    id: "visit_pro_han_minister",
    label: "拜访亲汉贵人",
    description: "夜访贵人居所，试探他对汉朝的真实态度，争取朝中内应。",
    targetCharacterId: "proHan",
    actionType: "contact",
    cost: 1,
    effects: { proHan: 8, hanPrestige: 3 },
    intelGained: ["intel_court_factions", "intel_king_mood"],
    evidenceGained: [],
    exposureChange: 5,
    unlocks: [],
    riskLevel: 2,
    baseSuccessRate: 0.85,
  },
  {
    id: "contact_translator",
    label: "拉拢译者",
    description: "私下约见译者，争取他的信任，了解前任汉使的真相。",
    targetCharacterId: "translator",
    actionType: "contact",
    cost: 1,
    effects: { proHan: 3 },
    intelGained: ["intel_previous_envoy_rumor", "intel_translator_fear"],
    evidenceGained: ["evidence_translator_testimony"],
    exposureChange: 5,
    unlocks: [],
    riskLevel: 2,
    baseSuccessRate: 0.75,
  },
  {
    id: "bribe_palace_attendant",
    label: "贿赂王庭近侍",
    description: "用丝绸和金币收买楼兰王身边的侍者，获取内部消息。",
    targetCharacterId: "king",
    actionType: "bribe",
    cost: 1,
    effects: { hanPrestige: -3, proHan: 5 },
    intelGained: ["intel_xiongnu_letter", "intel_guard_schedule"],
    evidenceGained: ["evidence_bribery_account"],
    exposureChange: 12,
    unlocks: [],
    riskLevel: 3,
    baseSuccessRate: 0.65,
  },
  {
    id: "investigate_previous_envoy",
    label: "调查前任汉使死因",
    description: "走访城中可能知情的人，查明前任汉使的真正死因。",
    targetCharacterId: undefined,
    actionType: "investigate",
    cost: 1,
    effects: { envoyHonor: 5, casusBelli: 3 },
    intelGained: ["intel_previous_envoy_truth"],
    evidenceGained: ["evidence_blood_letter", "evidence_broken_jie"],
    exposureChange: 10,
    unlocks: ["accuse_in_court"],
    riskLevel: 3,
    baseSuccessRate: 0.6,
  },
  {
    id: "scout_palace_guard",
    label: "探查王庭守卫",
    description: "暗中观察王庭卫兵的换防规律与人数部署。",
    targetCharacterId: undefined,
    actionType: "scout",
    cost: 1,
    effects: { casusBelli: 3 },
    intelGained: ["intel_guard_weakness"],
    evidenceGained: [],
    exposureChange: 12,
    unlocks: ["assassinate_king_prepared"],
    riskLevel: 4,
    baseSuccessRate: 0.7,
  },
  {
    id: "meet_loulan_merchant",
    label: "接触楼兰商人",
    description: "在城中市集找到经常往返汉地的楼兰商人，了解商道实情。",
    targetCharacterId: "proHan",
    actionType: "contact",
    cost: 1,
    effects: { tradeAccess: 8, proHan: 3 },
    intelGained: ["intel_trade_route", "intel_xiongnu_movement"],
    evidenceGained: ["evidence_xiongnu_raid_log"],
    exposureChange: 3,
    unlocks: [],
    riskLevel: 1,
    baseSuccessRate: 0.9,
  },
  {
    id: "spread_han_army_rumor",
    label: "散布汉军将至消息",
    description: "在城中散布汉朝大军已在玉门关集结的消息，制造心理压力。",
    targetCharacterId: undefined,
    actionType: "spread_rumor",
    cost: 1,
    effects: { kingFear: 10, xiongnuPressure: 5, proXiongnu: 3 },
    intelGained: [],
    evidenceGained: [],
    exposureChange: 18,
    unlocks: [],
    riskLevel: 4,
    baseSuccessRate: 0.6,
  },
  {
    id: "prepare_secret_blade",
    label: "准备刺王短刃",
    description: "暗中准备一把短刃，涂抹毒药，藏在袖中。为最坏的打算做准备。",
    targetCharacterId: undefined,
    actionType: "prepare_assassination",
    cost: 1,
    effects: { casusBelli: 8, envoyHonor: 3 },
    intelGained: [],
    evidenceGained: [],
    exposureChange: 20,
    unlocks: ["assassinate_king_prepared"],
    riskLevel: 5,
    baseSuccessRate: 0.5,
  },
];

/* ================================================================
 * 示例情报
 * ================================================================ */

export const INTEL_ITEMS: IntelItem[] = [
  {
    id: "intel_court_factions",
    title: "朝堂派系格局",
    description: "亲匈奴派以左大将为首，统辖楼兰过半武将；亲汉派以贵人为首，力量集中在文臣和商贾中。楼兰王在两者间摇摆。",
    reliability: "reliable",
    source: "亲汉贵人",
    relatedCharacterIds: ["proHan", "proXiongnu", "king"],
    tags: ["court", "factions"],
  },
  {
    id: "intel_king_mood",
    title: "楼兰王近期情绪",
    description: "楼兰王近日因匈奴使者催逼加重兵饷而烦躁，但对外仍维持强硬态度。",
    reliability: "reliable",
    source: "亲汉贵人",
    relatedCharacterIds: ["king"],
    tags: ["king", "mood"],
  },
  {
    id: "intel_translator_fear",
    title: "译者的恐惧",
    description: "译者似乎对亲匈大臣极为畏惧，每次提到左大将的名字都会不自觉地压低声音。",
    reliability: "uncertain",
    source: "译者本人",
    relatedCharacterIds: ["translator", "proXiongnu"],
    tags: ["translator", "fear"],
  },
  {
    id: "intel_xiongnu_letter",
    title: "亲匈大臣通敌密信",
    description: "左大将近期与匈奴使者秘密会面三次，似乎正在策划某个针对汉使的行动。",
    reliability: "uncertain",
    source: "宫中近侍",
    relatedCharacterIds: ["proXiongnu"],
    tags: ["xiongnu", "conspiracy"],
  },
  {
    id: "intel_guard_schedule",
    title: "王庭守卫轮换时间",
    description: "王庭东侧守卫每四个时辰换防一次，换防间隙有约一盏茶时间的空缺。",
    reliability: "reliable",
    source: "宫中近侍",
    relatedCharacterIds: [],
    tags: ["guard", "schedule"],
  },
  {
    id: "intel_previous_envoy_truth",
    title: "前任汉使死因真相",
    description: "前任汉使并非'暴病而亡'。他被密召入偏殿，亲匈大臣以伪造的'匈奴通敌信'构陷，楼兰王默许将其处决。译者被威胁改写了汉使的辩解之词。",
    reliability: "reliable",
    source: "多方印证",
    relatedCharacterIds: ["translator", "proXiongnu", "king"],
    tags: ["previous_envoy", "murder", "truth"],
  },
  {
    id: "intel_guard_weakness",
    title: "王庭东侧防御漏洞",
    description: "发现王庭东侧有一处年久失修的侧门，仅有一名守卫。可以通过此门秘密接近王座区域。",
    reliability: "reliable",
    source: "亲自侦察",
    relatedCharacterIds: [],
    tags: ["guard", "assassination"],
  },
  {
    id: "intel_xiongnu_movement",
    title: "匈奴骑兵动向",
    description: "据可靠消息，一支约三百人的匈奴骑兵已秘密抵达楼兰以北三日路程处。",
    reliability: "uncertain",
    source: "楼兰商人",
    relatedCharacterIds: ["proXiongnu"],
    tags: ["xiongnu", "military"],
  },
];

/* ================================================================
 * 示例证据
 * ================================================================ */

export const EVIDENCE_ITEMS: EvidenceItem[] = [
  {
    id: "evidence_broken_jie",
    title: "残破旌节",
    description: "前任汉使的旌节，已从中间折断。断口整齐，是被利器削断而非意外折断。上面沾有暗红色血渍。",
    strength: 0.9,
    canUseInCourt: true,
    unlockChoiceIds: ["accuse_in_court"],
    effectsWhenRevealed: { casusBelli: 15, envoyHonor: 10, kingAnger: 15, kingFear: 10 },
    tags: ["envoy", "evidence", "previous_envoy"],
  },
  {
    id: "evidence_blood_letter",
    title: "血书残片",
    description: "一片麻布残片，上面用血写着几个字：「左将…陷…王知…」——应是前任汉使死前留下的最后信息。",
    strength: 0.85,
    canUseInCourt: true,
    unlockChoiceIds: ["accuse_in_court"],
    effectsWhenRevealed: { casusBelli: 12, envoyHonor: 8, kingAnger: 10 },
    tags: ["envoy", "evidence", "previous_envoy"],
  },
  {
    id: "evidence_bribery_account",
    title: "亲匈大臣受贿账册",
    description: "近侍从亲匈大臣书房中偷出的账册副本，记录了匈奴单于以黄金和良马贿赂左大将的记录。",
    strength: 0.8,
    canUseInCourt: true,
    unlockChoiceIds: ["suppress_xiongnu_strong"],
    effectsWhenRevealed: { proXiongnu: -15, proHan: 10, casusBelli: 8 },
    tags: ["xiongnu", "bribery", "evidence"],
  },
  {
    id: "evidence_translator_testimony",
    title: "译者密证",
    description: "译者在反复权衡后提供的秘密证词。他承认亲匈大臣曾威胁他篡改前任汉使的翻译。",
    strength: 0.7,
    canUseInCourt: false,
    unlockChoiceIds: [],
    effectsWhenRevealed: { proXiongnu: -5, casusBelli: 8 },
    tags: ["translator", "testimony", "evidence"],
  },
  {
    id: "evidence_xiongnu_raid_log",
    title: "匈奴骑兵过境记录",
    description: "楼兰商人记录的匈奴骑兵在楼兰境内活动的详细日志，包括马匹数量和劫掠次数。",
    strength: 0.6,
    canUseInCourt: true,
    unlockChoiceIds: [],
    effectsWhenRevealed: { xiongnuPressure: 10, casusBelli: 5, tradeAccess: 5 },
    tags: ["xiongnu", "trade", "evidence"],
  },
];

/* ================================================================
 * 示例调查结果
 * ================================================================ */

export const INVESTIGATION_OUTCOMES: InvestigationOutcome[] = [
  {
    id: "outcome_reveal_conspiracy",
    title: "查明亲匈派陷害",
    description: "经过多方走访，你查清了真相：亲匈大臣左将伪造了通敌证据，栽赃前任汉使。楼兰王虽知实情，却因畏惧匈奴而默许了处决。",
    probabilityWeight: 35,
    effects: { casusBelli: 15, proHan: 8, envoyHonor: 8, proXiongnu: 5 },
    intelGained: ["intel_previous_envoy_truth"],
    evidenceGained: ["evidence_blood_letter", "evidence_broken_jie"],
    exposureChange: 10,
  },
  {
    id: "outcome_reveal_king_complicity",
    title: "发现楼兰王默许杀使",
    description: "你找到了一位在场的宫中侍者。他证实前任汉使被处决时，楼兰王就在屏风后全程目睹，未发一言阻止。",
    probabilityWeight: 25,
    effects: { kingAnger: 10, casusBelli: 12, envoyHonor: 5 },
    intelGained: ["intel_previous_envoy_truth"],
    evidenceGained: [],
    exposureChange: 15,
  },
  {
    id: "outcome_found_relics",
    title: "找到汉使遗物",
    description: "在亲汉贵人的秘密帮助下，你找到了前任汉使被草草掩埋的遗物——一柄折断的旌节和一片写有血字的麻布。",
    probabilityWeight: 25,
    effects: { envoyHonor: 10, casusBelli: 8, historianScore: 5 },
    intelGained: [],
    evidenceGained: ["evidence_broken_jie", "evidence_blood_letter"],
    exposureChange: 8,
  },
  {
    id: "outcome_no_results",
    title: "查无实据",
    description: "你在城中打听数日，得到的只有模糊的传闻和相互矛盾的证词。前任汉使的死因，似乎已被有心人刻意掩盖。",
    probabilityWeight: 15,
    effects: { xiongnuPressure: 3 },
    intelGained: [],
    evidenceGained: [],
    exposureChange: 10,
  },
];
